# spring configuration
spring:
   application:
      name: jblog06

   devtools:
      restart:
         enabled: true		
      livereload:
         enabled: true

   mvc:
      static-path-pattern: /assets/**	
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   web:
      resources:
         static-locations: [classpath:assets/, file:/jblog-uploads/]

   servlet:
      multipart:
         enabled: true
         max-file-size: 10485760
         max-request-size: 104857600
         file-size-threshold: 5242880

   # message resources(i18n)
   messages:
      basename: messages/message
      encoding: utf-8

# server configuration
server:
   port: 8080
   servlet:
      context-path: /jblog06

# logging
logging:
   config: classpath:logback.xml
